{
  "A11y dark A11y dark": "a11y-dark.css",
  "A11y light A11y light": "a11y-light.css",
  "Agate": "agate.css",
  "An old hope An old hope An old hope": "an-old-hope.css",
  "Androidstudio": "androidstudio.css",
  "Arduino light Arduino light": "arduino-light.css",
  "Arta": "arta.css",
  "Ascetic": "ascetic.css",
  "Atelier cave dark Atelier cave dark Atelier cave dark": "atelier-cave-dark.css",
  "Atelier cave light Atelier cave light Atelier cave light": "atelier-cave-light.css",
  "Atelier dune dark Atelier dune dark Atelier dune dark": "atelier-dune-dark.css",
  "Atelier dune light Atelier dune light Atelier dune light": "atelier-dune-light.css",
  "Atelier estuary dark Atelier estuary dark Atelier estuary dark": "atelier-estuary-dark.css",
  "Atelier estuary light Atelier estuary light Atelier estuary light": "atelier-estuary-light.css",
  "Atelier forest dark Atelier forest dark Atelier forest dark": "atelier-forest-dark.css",
  "Atelier forest light Atelier forest light Atelier forest light": "atelier-forest-light.css",
  "Atelier heath dark Atelier heath dark Atelier heath dark": "atelier-heath-dark.css",
  "Atelier heath light Atelier heath light Atelier heath light": "atelier-heath-light.css",
  "Atelier lakeside dark Atelier lakeside dark Atelier lakeside dark": "atelier-lakeside-dark.css",
  "Atelier lakeside light Atelier lakeside light Atelier lakeside light": "atelier-lakeside-light.css",
  "Atelier plateau dark Atelier plateau dark Atelier plateau dark": "atelier-plateau-dark.css",
  "Atelier plateau light Atelier plateau light Atelier plateau light": "atelier-plateau-light.css",
  "Atelier savanna dark Atelier savanna dark Atelier savanna dark": "atelier-savanna-dark.css",
  "Atelier savanna light Atelier savanna light Atelier savanna light": "atelier-savanna-light.css",
  "Atelier seaside dark Atelier seaside dark Atelier seaside dark": "atelier-seaside-dark.css",
  "Atelier seaside light Atelier seaside light Atelier seaside light": "atelier-seaside-light.css",
  "Atelier sulphurpool dark Atelier sulphurpool dark Atelier sulphurpool dark": "atelier-sulphurpool-dark.css",
  "Atelier sulphurpool light Atelier sulphurpool light Atelier sulphurpool light": "atelier-sulphurpool-light.css",
  "Atom one dark Atom one dark Atom one dark": "atom-one-dark.css",
  "Atom one dark reasonable Atom one dark reasonable Atom one dark reasonable Atom one dark reasonable": "atom-one-dark-reasonable.css",
  "Atom one light Atom one light Atom one light": "atom-one-light.css",
  "Brown paper Brown paper": "brown-paper.css",
  "Codepen embed Codepen embed": "codepen-embed.css",
  "Color brewer Color brewer": "color-brewer.css",
  "Darcula": "darcula.css",
  "Dark": "dark.css",
  "Default": "default.css",
  "Docco": "docco.css",
  "Dracula": "dracula.css",
  "Far": "far.css",
  "Foundation": "foundation.css",
  "Github": "github.css",
  "Github gist Github gist": "github-gist.css",
  "Gml": "gml.css",
  "Googlecode": "googlecode.css",
  "Gradient dark Gradient dark": "gradient-dark.css",
  "Gradient light Gradient light": "gradient-light.css",
  "Grayscale": "grayscale.css",
  "Gruvbox dark Gruvbox dark": "gruvbox-dark.css",
  "Gruvbox light Gruvbox light": "gruvbox-light.css",
  "Hopscotch": "hopscotch.css",
  "Hybrid": "hybrid.css",
  "Idea": "idea.css",
  "Ir black Ir black": "ir-black.css",
  "Isbl editor dark Isbl editor dark Isbl editor dark": "isbl-editor-dark.css",
  "Isbl editor light Isbl editor light Isbl editor light": "isbl-editor-light.css",
  "Kimbie.dark": "kimbie.dark.css",
  "Kimbie.light": "kimbie.light.css",
  "Lightfair": "lightfair.css",
  "Lioshi": "lioshi.css",
  "Magula": "magula.css",
  "Mono blue Mono blue": "mono-blue.css",
  "Monokai": "monokai.css",
  "Monokai sublime Monokai sublime": "monokai-sublime.css",
  "Night owl Night owl": "night-owl.css",
  "Nnfx": "nnfx.css",
  "Nnfx dark Nnfx dark": "nnfx-dark.css",
  "Nord": "nord.css",
  "Obsidian": "obsidian.css",
  "Ocean": "ocean.css",
  "Paraiso dark Paraiso dark": "paraiso-dark.css",
  "Paraiso light Paraiso light": "paraiso-light.css",
  "Pojoaque": "pojoaque.css",
  "Purebasic": "purebasic.css",
  "Qtcreator_dark": "qtcreator_dark.css",
  "Qtcreator_light": "qtcreator_light.css",
  "Railscasts": "railscasts.css",
  "Rainbow": "rainbow.css",
  "Routeros": "routeros.css",
  "School book School book": "school-book.css",
  "Shades of purple Shades of purple Shades of purple": "shades-of-purple.css",
  "Solarized dark Solarized dark": "solarized-dark.css",
  "Solarized light Solarized light": "solarized-light.css",
  "Srcery": "srcery.css",
  "Stackoverflow dark Stackoverflow dark": "stackoverflow-dark.css",
  "Stackoverflow light Stackoverflow light": "stackoverflow-light.css",
  "Sunburst": "sunburst.css",
  "Tomorrow": "tomorrow.css",
  "Tomorrow night Tomorrow night": "tomorrow-night.css",
  "Tomorrow night blue Tomorrow night blue Tomorrow night blue": "tomorrow-night-blue.css",
  "Tomorrow night bright Tomorrow night bright Tomorrow night bright": "tomorrow-night-bright.css",
  "Tomorrow night eighties Tomorrow night eighties Tomorrow night eighties": "tomorrow-night-eighties.css",
  "Vs": "vs.css",
  "Vs2015": "vs2015.css",
  "Xcode": "xcode.css",
  "Xt256": "xt256.css",
  "Zenburn": "zenburn.css"
}
