# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - prep
  - test
  - build
  - release

variables:
  DS_EXCLUDED_ANALYZERS: "gemnasium-maven, gemnasium-python"

.standard-rules:       # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.python-common:
  needs:
    - job: docker-build
      optional: true
  image: registry.gitlab.com/mdhr-extension/markdown-here-revival:ci
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip

.python-testing:
  extends:
    - .python-common
  stage: test
  before_script:
    - python --version ; pip --version  # For debugging
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements/dev.txt
    - TXT_RED="\e[31m" && TXT_GREEN="\e[32m" && TXT_RESET="\e[39m"
  after_script:
    - if [[ "$CI_JOB_STATUS" == "canceled" ]]; then exit 0; fi
    - |
      if [[ "$RV" -gt 0 ]]; then
        echo -e "${TXT_RED}Test ${CI_JOB_NAME} failed${TXT_RESET}\n"
        jq . ${REPORT_FILENAME}
        exit $RV
      else
        echo -e "${TXT_GREEN}Test ${CI_JOB_NAME} succeeded${TXT_RESET}\n"
      fi

docker-build:
  extends: .standard-rules
  image: docker:cli
  stage: prep
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" CI/.
    - docker push "$DOCKER_IMAGE_NAME"
    - docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:ci"
    - docker push "$CI_REGISTRY_IMAGE:ci"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - changes:
        - CI/Dockerfile

lint:ruff-format:
  extends:
    - .standard-rules
    - .python-testing
  variables:
    FORMAT_DIFF: format_diff.diff
    REPORT_FILENAME: black-code-quality-report.json
  script:
    - RV=0
    - ruff format --diff --verbose > $FORMAT_DIFF || RV=$?
    - echo "RV=$RV" >> $GITLAB_ENV
    - black-codeclimate $FORMAT_DIFF > $REPORT_FILENAME
  artifacts:
    when: always
    reports:
      codequality: $CI_PROJECT_DIR/$REPORT_FILENAME
    paths:
      - $REPORT_FILENAME

lint:ruff:
  extends:
    - .standard-rules
    - .python-testing
  variables:
    REPORT_FILENAME: ruff-code-quality-report.json
  script:
    - ruff check --output-format=gitlab > $REPORT_FILENAME
    - echo "RV=$?" >> $GITLAB_ENV
  artifacts:
    when: always
    reports:
      codequality: $CI_PROJECT_DIR/$REPORT_FILENAME
    paths:
      - $REPORT_FILENAME
  rules:
    - when: never  # TODO: Enable Ruff in CI

mdhr-build:
  extends:
    - .standard-rules
    - .python-common
  stage: build
  before_script:
    - python --version ; pip --version  # For debugging
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements/requirements.txt
  script:
    - make ci
  artifacts:
    paths:
      - web-ext-artifacts/markdown-here-revival.xpi
      - notes.md
    reports:
      dotenv: version.env

mdhr-release:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  image: "registry.gitlab.com/mdhr-extension/markdown-here-revival:ci"
  needs:
    - job: mdhr-build
      artifacts: true
    - job: docker-build
      optional: true
  variables:
      XPI_FILENAME: "markdown_here_revival-${PACKAGE_VERSION}.xpi"
  script:
    - echo "Running the release job."
    - |
      GLAB_VERSION=$(
        git ls-remote -t --sort -version:refname https://gitlab.com/gitlab-org/cli | head -n 1 | awk '{
        ref=$2
        sub(/refs\/tags\/v/, "", ref)
        print ref
        }'
      )
      GLAB_URL="https://gitlab.com/gitlab-org/cli/-/releases/v${GLAB_VERSION}/downloads/glab_${GLAB_VERSION}_linux_amd64.tar.gz"
      wget -qO- "${GLAB_URL}" | tar xvz --strip-components=1 bin/glab
    - mv -f web-ext-artifacts/markdown-here-revival.xpi web-ext-artifacts/${XPI_FILENAME}
    - ./glab auth login --job-token $CI_JOB_TOKEN --hostname $CI_SERVER_HOST --api-protocol $CI_SERVER_PROTOCOL
    - > 
      ./glab release create ${RELEASE_NAME} \
        --name ${RELEASE_NAME} \
        -F ./notes.md \
        web-ext-artifacts/${XPI_FILENAME}

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
