
stages:
  - build
  - release

.standard-rules:       # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


docker-build:
  extends: .standard-rules
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" CI/.
    - docker push "$DOCKER_IMAGE_NAME"
    - docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:ci"
    - docker push "$CI_REGISTRY_IMAGE:ci"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - changes:
        - CI/Dockerfile

mdhr-build:
  extends: .standard-rules
  stage: build
  needs:
    - job: docker-build
      optional: true
  image: "registry.gitlab.com/jfx2006/markdown-here-revival:ci"
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - .pnpm-store
  before_script:
  - pnpm config set store-dir .pnpm-store
  - python --version ; pip --version  # For debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements/requirements.txt
  script:
  - make ci
  artifacts:
    paths:
      - web-ext-artifacts/markdown-here-revival.xpi
      - notes.md
    reports:
      dotenv: version.env

mdhr-release:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  image: "registry.gitlab.com/jfx2006/markdown-here-revival:ci"
  needs:
    - job: mdhr-build
      artifacts: true
    - job: docker-build
      optional: true
  variables:
      XPI_FILENAME: "markdown_here_revival-${PACKAGE_VERSION}.xpi"
  script:
    - echo "Running the release job."
    - mv -f web-ext-artifacts/markdown-here-revival.xpi web-ext-artifacts/${XPI_FILENAME}
    - glab auth login --job-token $CI_JOB_TOKEN --hostname $CI_SERVER_HOST --api-protocol $CI_SERVER_PROTOCOL
    - > 
      glab release create ${RELEASE_NAME} \
        --name ${RELEASE_NAME} \
        -F ./notes.md \
        web-ext-artifacts/${XPI_FILENAME}
