version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
